Repository skypjack/uvw, pull requests merged in 2023-02, with the labels that each got.

#273 Include cstdint where uintX_t is used
  src/uvw/emitter.h
  src/uvw/thread.h
  src/uvw/timer.h
  src/uvw/type_info.hpp
  src/uvw/util.h
Labels: enhancement

#274 Add Vcpkg badge
  README.md
Labels: documentation

#275 avoid cmake complaining about using VERSION keyword
  .gitignore
  CMakeLists.txt
Labels: build system
