Repository skypjack/uvw, pull requests merged in 2023-08, with the labels that each got.

#295 Fix minor typo in CMakeLists.txt
  CMakeLists.txt
Labels: documentation

#297 loop: rename variable to fix `-Wshadow` warning
  src/uvw/loop.h
Labels: enhancement

#296 uv_type: supress `-Werror=unused` compiler error
  src/uvw/uv_type.hpp
Labels: enhancement

#300 tty: remove unnecessary semi-colon
  src/uvw/tty.cpp
Labels: enhancement

#301 type_info: avoid gcc-7 `-Wsign-conversion warning`
  src/uvw/type_info.hpp
Labels: enhancement

#299 pipe: hide `uvw::pipe_handle::connect()` `-Wsign-conversion` warning
  src/uvw/pipe.cpp
Labels: enhancement

#298 util: fix `-Wsign-conversion` in ip_addr()
  src/uvw/util.cpp
Labels: triage

#303 uv_type: make `~uv_type()` destructor protected
  src/uvw/uv_type.hpp
Labels: triage
